#!/bin/bash
set -ue
set -o pipefail # important for when a field doesn't exist

PASS_STORE=~/.password-store
USER_FIELD="user"

function usage () {
cat <<EOF
Usage: $(basename $0) [-p|-u|-o|-i] [-copy|-show|-paste] PASSNAME

OPTIONS

  -p        Select password field, which should be the first line. (default)
  -u        Select \`$USER_FIELD:\` field.
  -o        Select otp field using \`pass otp\`.
  -f FIELD  Select a field of the given password entry.
  -i        Interactively prompt for a field.

OPTIONS (only useful for AHK script)

  -l     List all paswords entries.
  -lf    List all fields of a password entry.

  -copy  Copy to xclip clipboard selection (default).
  -show  Print on stdout.
  -paste Paste to xclip primary selection.

  -v     Debug mode.
EOF
}

function list(){
  cd $PASS_STORE
  find -not -path "*/.*" | tail -n +2 | sed -E 's/\.gpg(\x1B\[[0-9]+m)?( ->|$)/\1\2/g' | sed 's@^\./@@'
  cd - > /dev/null
}

mode=pwd
verbose=false
action=copy

positional=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -p|-pwd)
    mode=pwd
    shift
    ;;
    -u|-user)
    mode=user
    shift
    ;;
    -o|-otp)
    mode=otp
    shift
    ;;
    -f|-field)
    mode=field
    input_field=$2
    shift; shift
    ;;
    -lf|-list-fields)
    mode=list_fields
    shift
    ;;
    -i|-interactive)
    mode=interactive
    shift
    ;;
    -l)
    list
    exit 0
    ;;
    -paste)
    action=paste
    shift
    ;;
    -copy)
    action=copy
    shift
    ;;
    -show)
    action=show
    shift
    ;;
    -v)
    verbose=true
    shift
    ;;
    -h|-help|--help)
    usage
    exit 0
    ;;
    -*) # unknown option
    echo "error, unknown option: $1"
    exit 1
    ;;
    *) # passname
    positional+=("$1") # save it in an array for later
    shift
    ;;
esac
done
set -- "${positional[@]}" # restore positional parameters

# check $# == 1
if [[ $# != 1 ]]; then
  shift
  echo "error, additional argument(s): $@"
  exit 1
fi

passname=$1

function process(){
  case $action in
  copy)
    copy
    ;;
  show)
    show
    ;;
  paste)
    paste
    ;;
  *)
    echo "error, unknown action: $action"
    exit 1
    ;;
  esac
}

function copy(){
  xclip -selection clipboard
}

function paste(){
  xclip -selection primary
  xclip -o -selection primary
}

function show(){
  cat | tr -d \\n
}

function getfield(){
  local passname=$1
  local field=$2
  local match=$(pass $passname | grep "^$field:")
  if [[ "x$match" == "x" ]]; then
    echo "error, no field $field in $passname"
    exit 1
  else
    echo $match | cut -d \: -f2- | sed 's/^ *//' | sed 's/ *$//' | process
  fi
}

$verbose && set -x

function list_fields(){
  local passname=$1
  # remove password field, '---' line, and send the rest
  pass $passname | tail -n +2 | grep \: | cut -d \: -f1
}

function prompt_for_field(){
  local passname=$1
  # remove password field, '---' line, and send the rest to fzf
  field=$(pass $passname | tail -n +2 | grep \: | cut -d \: -f1 | fzf)
  echo $field
}

case $mode in
pwd)
  pass $passname | head -n1 | process
  ;;
user)
  getfield $passname $USER_FIELD
  ;;
otp)
  pass otp $passname | process
  ;;
field)
  getfield $passname $input_field
  ;;
list_fields)
  list_fields $passname
  ;;
interactive)
  input=$(prompt_for_field $passname)
  getfield $passname $input
  ;;
*)
  echo "error, unknown mode: $mode"
  exit 1
  ;;
esac
